# Site settings
title: Vighnesh Birodkar
email: vighnesh.birodkar@featurex.ai
description:  This is the personal portfolio of Vighnesh Birodkar.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: #jekyllrb
github_username:  vighneshbirodkar

# Build settings
markdown: kramdown
